server:
  port: 8085
  servlet:
    context-path: /api/notification

spring:
  application:
    name: sebm-notification-service

  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:29578/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: RxAHOOQJjTtBblTpadijgyIWmArpvibI
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sebm.notifications@gmail.com}
    password: ${MAIL_PASSWORD:mysr cwqu lybt mdmv}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  # ✅ RabbitMQ 放在 spring 下
  rabbitmq:
    host: hopper.proxy.rlwy.net
    port: 50343
    username: test
    password: test
    virtual-host: /
    ssl:
      enabled: false
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
  # ✅ Nacos 放在 spring.cloud 下
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
  data:
    redis:
      host: caboose.proxy.rlwy.net
      port: 13462
      username: default
      password: ekseulHMMJJMoAFIOLchTXsnRDbpMHff
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
resend:
  api-key: ${RESEND_API_KEY:re_eZiYFxTN_DZMychBGRpAR2qDv5N9x7hB8}
  from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
  from-name: ${RESEND_FROM_NAME:SEBM Notification System}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

aliyun:
  oss:
    endpoint: oss-ap-southeast-1.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: sebm

knife4j:
  enable: true
  setting:
    language: zh_cn
