server:
  port: 8083
  servlet:
    context-path: /api/device
spring:
  application:
    name: sebm-device-service
  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:29578/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: RxAHOOQJjTtBblTpadijgyIWmArpvibI
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
  cache:
    type: redis
  data:
    redis:
      host: caboose.proxy.rlwy.net
      port: 13462
      username: default
      password: ekseulHMMJJMoAFIOLchTXsnRDbpMHff

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

aliyun:
  oss:
    endpoint: oss-ap-southeast-1.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: sebm

knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  endpoints:
    web:
      exposure:
        include: "*"          # 允许暴露所有 actuator 端点
  endpoint:
    prometheus:
      enabled: true           # 启用 prometheus 端点
  prometheus:
    metrics:
      export:
        enabled: true
