name: Build Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [sebm-gateway, sebm-user-service, sebm-borrow-service,sebm-device-service,sebm-maintenance-service] # 可添加更多服务

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 构建 Maven 项目
      - name: Build with Maven
        working-directory: ./services/${{ matrix.service }}
        run: mvn clean package -DskipTests
